// Mocks generated by Mockito 5.4.6 from annotations
// in gazzer/test/auth/register/register_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i9;
import 'package:gazzer/core/data/network/result_model.dart' as _i4;
import 'package:gazzer/features/auth/common/data/auth_response.dart' as _i5;
import 'package:gazzer/features/auth/common/domain/entities/client_entity.dart'
    as _i8;
import 'package:gazzer/features/auth/register/data/register_repo_imp.dart'
    as _i2;
import 'package:gazzer/features/auth/register/data/register_request.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RegisterRepoImp].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterRepoImp extends _i1.Mock implements _i2.RegisterRepoImp {
  MockRegisterRepoImp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get canChangePhone =>
      (super.noSuchMethod(
            Invocation.getter(#canChangePhone),
            returnValue: false,
          )
          as bool);

  @override
  set canChangePhone(bool? _canChangePhone) => super.noSuchMethod(
    Invocation.setter(#canChangePhone, _canChangePhone),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<_i4.Result<_i5.AuthResponse>> register(_i6.RegisterRequest? req) =>
      (super.noSuchMethod(
            Invocation.method(#register, [req]),
            returnValue: _i3.Future<_i4.Result<_i5.AuthResponse>>.value(
              _i7.dummyValue<_i4.Result<_i5.AuthResponse>>(
                this,
                Invocation.method(#register, [req]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AuthResponse>>);

  @override
  _i3.Future<_i4.Result<String>> resendOtp(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#resendOtp, [sessionId]),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i7.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#resendOtp, [sessionId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);

  @override
  _i3.Future<_i4.Result<String>> resend([String? data]) =>
      (super.noSuchMethod(
            Invocation.method(#resend, [data]),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i7.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#resend, [data]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);

  @override
  _i3.Future<_i4.Result<String>> editPhoneNumber(
    String? sessionId,
    String? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editPhoneNumber, [sessionId, code]),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i7.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#editPhoneNumber, [sessionId, code]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);

  @override
  _i3.Future<_i4.Result<String>> onChangePhone(
    String? newPhone, [
    String? data,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#onChangePhone, [newPhone, data]),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i7.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#onChangePhone, [newPhone, data]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);

  @override
  _i3.Future<_i4.Result<String>> verifyOTP(String? sessionId, String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOTP, [sessionId, code]),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i7.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#verifyOTP, [sessionId, code]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);

  @override
  _i3.Future<_i4.Result<String>> verify(String? otpCode, [String? data]) =>
      (super.noSuchMethod(
            Invocation.method(#verify, [otpCode, data]),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i7.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#verify, [otpCode, data]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);

  @override
  void setAuthUser(_i8.ClientEntity? client, String? token) =>
      super.noSuchMethod(
        Invocation.method(#setAuthUser, [client, token]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<_i4.Result<T>> call<T>({
    required _i3.Future<_i9.Response<dynamic>> Function()? apiCall,
    required T Function(_i9.Response<dynamic>)? parser,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#apiCall: apiCall, #parser: parser}),
            returnValue: _i3.Future<_i4.Result<T>>.value(
              _i7.dummyValue<_i4.Result<T>>(
                this,
                Invocation.method(#call, [], {
                  #apiCall: apiCall,
                  #parser: parser,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<T>>);
}
