// Mocks generated by Mockito 5.4.6 from annotations
// in gazzer/test/core/core_generator.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:gazzer/core/data/network/api_client.dart' as _i5;
import 'package:gazzer/core/data/network/crashlytics_repo_imp.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:shared_preferences/shared_preferences.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCancelToken_1 extends _i1.SmartFake implements _i2.CancelToken {
  _FakeCancelToken_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CrashlyticsRepoImp].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashlyticsRepoImp extends _i1.Mock
    implements _i3.CrashlyticsRepoImp {
  MockCrashlyticsRepoImp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> sendToCrashlytics(
    Object? error,
    StackTrace? stack, {
    bool? isFatal = true,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendToCrashlytics,
              [error, stack],
              {#isFatal: isFatal, #reason: reason},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i5.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseURL =>
      (super.noSuchMethod(
            Invocation.getter(#baseURL),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#baseURL),
            ),
          )
          as String);

  @override
  Duration get timeOut =>
      (super.noSuchMethod(
            Invocation.getter(#timeOut),
            returnValue: _FakeDuration_0(this, Invocation.getter(#timeOut)),
          )
          as Duration);

  @override
  _i2.CancelToken get cancelToken =>
      (super.noSuchMethod(
            Invocation.getter(#cancelToken),
            returnValue: _FakeCancelToken_1(
              this,
              Invocation.getter(#cancelToken),
            ),
          )
          as _i2.CancelToken);

  @override
  bool get isDisconected =>
      (super.noSuchMethod(Invocation.getter(#isDisconected), returnValue: false)
          as bool);

  @override
  set cancelToken(_i2.CancelToken? _cancelToken) => super.noSuchMethod(
    Invocation.setter(#cancelToken, _cancelToken),
    returnValueForMissingStub: null,
  );

  @override
  set isDisconected(bool? _isDisconected) => super.noSuchMethod(
    Invocation.setter(#isDisconected, _isDisconected),
    returnValueForMissingStub: null,
  );

  @override
  void changeLocale(String? languageCode) => super.noSuchMethod(
    Invocation.method(#changeLocale, [languageCode]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.Response<dynamic>> get({
    required String? endpoint,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [], {
              #endpoint: endpoint,
              #queryParameters: queryParameters,
              #headers: headers,
              #cancelToken: cancelToken,
            }),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(#get, [], {
                  #endpoint: endpoint,
                  #queryParameters: queryParameters,
                  #headers: headers,
                  #cancelToken: cancelToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> post({
    required String? endpoint,
    required dynamic requestBody,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    Duration? customRequestDuration,
    void Function(int, int)? onSendProgress,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#post, [], {
              #endpoint: endpoint,
              #requestBody: requestBody,
              #queryParameters: queryParameters,
              #headers: headers,
              #customRequestDuration: customRequestDuration,
              #onSendProgress: onSendProgress,
              #cancelToken: cancelToken,
            }),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(#post, [], {
                  #endpoint: endpoint,
                  #requestBody: requestBody,
                  #queryParameters: queryParameters,
                  #headers: headers,
                  #customRequestDuration: customRequestDuration,
                  #onSendProgress: onSendProgress,
                  #cancelToken: cancelToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> delete({
    required String? endpoint,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #endpoint: endpoint,
              #queryParameters: queryParameters,
              #headers: headers,
            }),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(#delete, [], {
                  #endpoint: endpoint,
                  #queryParameters: queryParameters,
                  #headers: headers,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i7.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i4.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
