// Mocks generated by Mockito 5.4.6 from annotations
// in gazzer/test/features/auth/login/login_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i6;
import 'package:gazzer/core/data/network/error_models.dart' as _i7;
import 'package:gazzer/core/data/network/result_model.dart' as _i4;
import 'package:gazzer/features/auth/login/data/login_repo_imp.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LoginRepoImp].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginRepoImp extends _i1.Mock implements _i2.LoginRepoImp {
  MockLoginRepoImp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<String>> login(String? phone, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [phone, password]),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i5.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#login, [phone, password]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);

  @override
  _i3.Future<_i4.Result<T>> call<T>({
    required _i3.Future<_i6.Response<dynamic>> Function()? apiCall,
    required T Function(_i6.Response<dynamic>)? parser,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#apiCall: apiCall, #parser: parser}),
            returnValue: _i3.Future<_i4.Result<T>>.value(
              _i5.dummyValue<_i4.Result<T>>(
                this,
                Invocation.method(#call, [], {
                  #apiCall: apiCall,
                  #parser: parser,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<T>>);

  @override
  _i7.BaseError? isTokenExpired(Object? error) =>
      (super.noSuchMethod(Invocation.method(#isTokenExpired, [error]))
          as _i7.BaseError?);
}
