// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJq95ahVMapOhxJVjLmJ9-l0d_g2qTYqM',
    appId: '1:426479468960:web:9ee931ff4a2dd6ff31a4c5',
    messagingSenderId: '426479468960',
    projectId: 'azgazzer',
    authDomain: 'azgazzer.firebaseapp.com',
    storageBucket: 'azgazzer.firebasestorage.app',
    measurementId: 'G-Z127WSB8R1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlzNdub1O9O4YhJxDXHczxp4B_KkiLAuw',
    appId: '1:426479468960:android:aa9ab90f82111e3a31a4c5',
    messagingSenderId: '426479468960',
    projectId: 'azgazzer',
    storageBucket: 'azgazzer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBW7dELsPCNoaPyvwNET4X7t0_ZfEOzaw',
    appId: '1:426479468960:ios:adc0e7cffeb6885531a4c5',
    messagingSenderId: '426479468960',
    projectId: 'azgazzer',
    storageBucket: 'azgazzer.firebasestorage.app',
    iosClientId: '426479468960-o81gqb39gcnl6u9sapr0fudk6u3rsbun.apps.googleusercontent.com',
    iosBundleId: 'com.az.gazzer',
  );

}